### ISSUE TITLE
Error occurred when searching my articles.

### ISSUE THREAD

**Issue by mono0926** [uetchy/alfred-qiita-workflow#3]
I got this error after typed `qiita my 便利`.

```
2015/06/28 09:28:21 Created</subtitle><icon>icon.png</icon></item></items>
[ERROR: alfred.workflow.input.scriptfilter] Code 1: ./commands/my.rb:22:in `scan': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (Encoding::CompatibilityError)
	from ./commands/my.rb:22:in `block in <main>'
	from ./commands/my.rb:22:in `select!'
	from ./commands/my.rb:22:in `<main>'
```

## Environment

- OS X 10.11 Beta (15A279b)
- Alfred 2.7.1

**Comment by uetchy** [comment]
Can you tell me your Ruby version with `/usr/bin/ruby -v` in Terminal.app?

**Comment by mono0926** [comment]
ヽ(・ω・｀）

```
➜  ~  /usr/bin/ruby -v   
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
```

**Comment by uetchy** [comment]
I just re-wrote this workflow in golang and it seems work nicely.
You can test this version on [pre-release tag](https://github.com/uetchy/alfred-qiita-workflow/releases/tag/pre-release).

**Comment by mono0926** [comment]
Thank you very much!!
It seems working fine :+1:

**Comment by uetchy** [comment]
[Released](https://github.com/uetchy/alfred-qiita-workflow/releases/tag/v2.0.0).
Thank you for your help!
