### ISSUE TITLE
qiita stocks で認証ユーザのストックが対象とならない

### ISSUE THREAD

**Issue by DriftwoodJP** [uetchy/alfred-qiita-workflow#4]
ワークフローを利用しております。ありがとうございます。

`qiita stocks` の検索で表題の件に気づきました。
stocks.go をのぞいたところ、下記が影響しているように見えました。

```
items, _, _ := client.Users.Stocks("uetchy", nil)
```

golang について分からないため曖昧な issue で申し訳ないですが、ご確認頂けると幸いです。

**Comment by uetchy** [comment]
バグを確認しました。ご報告ありがとうございます。

**Comment by uetchy** [comment]
この[PR](https://github.com/uetchy/alfred-qiita-workflow/pull/5)で修正しました。次のバージョンをリリースするのでお待ちください。

**Comment by uetchy** [comment]
[v2.1.0](https://github.com/uetchy/alfred-qiita-workflow/releases/tag/v2.1.0)をリリースしました。

**Comment by DriftwoodJP** [comment]
動きました。ありがとうございます。:)
